name: 'Lint and Auto-Fix Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint and Auto-Fix Python Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Auto-format Python files with Black
      run: |
        black .

    - name: Commit and Push changes if needed (Python)
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git diff --cached --quiet || (git commit -m "Auto-format Python code with Black" && git push)

  lint_js:
    name: Lint and Auto-Fix JavaScript Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # lebih baru dari 14
    
    - name: Install ESLint
      run: npm install --global eslint

    - name: Initialize ESLint (if needed)
      run: |
        if [ ! -f .eslintrc.js ] && [ ! -f .eslintrc.json ]; then
          eslint --init
        fi

    - name: Auto-fix JavaScript files with ESLint
      run: |
        eslint ./server/database --ext .js --fix || true

    - name: Commit and Push changes if needed (JavaScript)
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git diff --cached --quiet || (git commit -m "Auto-fix JavaScript code with ESLint" && git push)
