name: 'Lint Code'
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_and_fix_python:
    name: Lint and Fix Python Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Auto-fix Python Code with Black
      run: |
        black .  # format all Python files recursively
        echo "Auto-formatted all Python files successfully"

  lint_and_fix_js:
    name: Lint and Fix JavaScript Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install JavaScript dependencies
      run: |
        npm install eslint --global

    - name: Auto-fix JavaScript Code with ESLint
      run: |
        # Make sure you have a .eslintrc.json config file
        find ./server/database -name "*.js" -exec eslint --fix {} +
        echo "Auto-fixed all JavaScript files successfully"
